### PR TITLE
Update cell order and nomeclature in Preview Screen

### PR DESCRIPTION
**Pull request by oliver-was-here**
Story: https://www.pivotaltracker.com/story/show/156698685

See 311d2b4 for relevant changes.

#### Blocked
The PR to add branding to the SDK also introduced the new row for Account. This story is rebased on the pending commits found in https://github.com/tradingticket/TradeItIosTicketSDK2/pull/329.

### CODE REVIEW

**Comment by jsom** [comment]
Kind of eh about changing `quantity` to `shares` but eh! Were there no other reorderings required in the story?

**Comment by oliver-was-here** [comment]
@jsom had the same thought, but orders are orders and "quantities" are "shares" ¯\_(ツ)_/¯

**Comment by oliver-was-here** [comment]
gngn

**Comment by oliver-was-here** [comment]
accidentally closed. smdh.

**Comment by oliver-was-here** [comment]
Merging into #329 (review) to avoid conflicts that would ensue from rebasing #329 (review) onto the most up to date develop. git rerere was not doing enough for us here.

**Pull request closed without merging**
